### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by hannes-thaller** [Mondego/oreo#5]
Is there a truly working version of Oreo?
The original artifact is full of null pointers, and the current version comes with null pointers in the SearchManager (418).
I debugged and simplified lots of stuff but to be honest, the repository is a mess.

Now I am at the point where the clone detector searchers for the index
`17:21:24.681 [main] ERROR com.mondego.indexbased.SearchManager - $rootPATH/index/1/candidates.file (No such file or directory)exiting`

Which script or where is the "index" generated?

Thanks

**Comment by farimaf** [comment]
Hello,
Thank you for your interest in Oreo.
The working repository of Oreo is located in this address: [Oreo Artifact](https://github.com/Mondego/oreo-artifact) Have you tried the version in this repo? If yes, would please indicate what error you are facing with that version?
Thanks.

**Comment by hannes-thaller** [comment]
Ahh, thank you for the pointer, no I have not seen this repository yet.
